"""empty message

Revision ID: 5882757dd0fe
Revises: 0bc5a3a40495
Create Date: 2021-09-16 19:59:04.159013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5882757dd0fe'
down_revision = '0bc5a3a40495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'seeking_descripotion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_descripotion', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
