"""empty message

Revision ID: 69533baa7fa3
Revises: 5882757dd0fe
Create Date: 2021-09-16 20:14:31.306954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69533baa7fa3'
down_revision = '5882757dd0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
